from python:3.7.9-slim

EXPOSE 8080

COPY requirements.txt app/requirements.txt
RUN pip install -r requirements.txt

COPY . /app
WORKDIR /app


# RUN pip install Flask gunicorn


# CMD exec gunicorn --bind 0.0.0.0:$PORT --workers=4 --threads 8 --timeout 0 app:app
# CMD ['python', 'app.py']
ENTRYPOINT ["Anamoly", "run", "app.py", "--server.port=8080", "--server.address=0.0.0.0"]
