FROM python:3.7

COPY ./requirements.txt /app/requirements.txt
COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install Flask gunicorn
ENV PORT 8080
ENV HOST 0.0.0.0
EXPOSE 808
ENTRYPOINT [ "python" , "app.py"]
