FROM python:3.7

COPY ./requirements.txt /app/requirements.txt
COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install Flask gunicorn

EXPOSE $port
ENTRYPOINT [ "Python", "-m", "flask", "run"]
CMD [ "app.py" ]
